### ISSUE TITLE
(feat) Accept numeric IDs into the bhFindPatient directive

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#131]
Our current human readable identifiers are difficult to type and will likely result in carpal tunnel syndrome if typed repeatedly.  For institutions that only have a single project, we could easily accept a numeric input -- instead of `PA.HEV.1`, the users could simply type `1`.

I propose that we implement this feature with the following conditions:
 1. The search will only look at the `reference` column in the database.  If the result returns more than one, it should report a warning to the user (`text-warning`) that says "ambiguous identifier - please type the full identifier into the input".
 2. If there is only one patient for each reference, we can simply default to the current behavior of displaying the patient name.
 4. A 404 should be an error.

**Comment by DedrickEnc** [comment]
Can you be more clear about the point 2?

**Comment by jniles** [comment]
Sure -

We currently show the patient name when the bhFindPatient component succeeds in finding a patient.  The input is also colored green.  This behavior should stay the same.

**Comment by sfount** [comment]
As an addition to this issue I suggest that instead of only looking at the `reference` field we use the project that the user is currently logged into instead. 

In this way if you are logged into the hospital project and enter `1` to the find patient utility it will request `PA.HSP.1` - this will always be a non-ambiguous record. 

The problem with using the reference field is that if there are ever two projects this feature will never work. 

Both the client and the server have access to the current project that the user is logged into via the user's session. I recommend this is used to augment the request before the database is searched. This could either be done in a server controller or a client service.
