### ISSUE TITLE
(bug): Registry totals do not ignore canceled/reverse records

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#139]
In the cash payments and the invoice registries, the totals at the bottom of the page are not necessarily reflective of the amount of money collected/recorded because some of the transactions may be reversed.  In our totaling algorithms, we need to make sure that these records are taken into account and properly treated.

**Comment by jniles** [comment]
I'll take this one.

**Comment by sfount** [comment]
I would suggest that the totalling algorithms continue to total what is in the view. If we make an exception for some cases it could be a confusing user experience not knowing exactly what is totalled and what the rules are. 

What if we allowed you to filter out cash payments/ invoices that have been reversed so that the totals only show records that have not been invalidated and reflect actual totals?
