### ISSUE TITLE
Move invoice currency to settings page

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#154]
Currently a number of our modules allow the current exchange of today to be shown on invoices; this feature implements a flag on every relevant page.

We also have a number of settings on the settings page 
* Switch between POS receipts and full report type receipts 
* Switch between full A6 Patient cards and smaller 'simple' cards

I propose that we add showing the currency on invoices in a different currency to the settings page - once all system settings are in the same place we can discuss the ideal way to present these settings to users.

**Comment by jniles** [comment]
I would call this "Receipt Currency" or something similar ... if I understand correctly, this is the currency that is exchanged, not necessarily the currency an invoice is made in, correct?

**Comment by sfount** [comment]
You are correct. This is just the currency that the invoice total is converted to to be displayed at the bottom of the invoice. It has no effect on the value of the invoice.

I think invoicing in multiple currencies is discussed in another issue but I cannot find it here.

**Comment by DedrickEnc** [comment]
Can I have more explanation? I am not understanding.

**Comment by jniles** [comment]
This issue just asks that the Receipt Currency selection tool @sfount built be moved to the Settings page instead of on top of the invoice page.  See below:

![currencyselect](https://cloud.githubusercontent.com/assets/896472/22372403/c70ae930-e49c-11e6-9cf2-1a1baaba3749.png)
_This should be on the settings page, either in this form or as a radio select button_.

**Comment by jniles** [comment]
Closed in #209.
