### ISSUE TITLE
bug(vouchers) Journal Vouchers (complex) errors on creation

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#232]
The complex journal vouchers module does not successfully reset after a voucher has been created. 

After completing a journal voucher the following message is displayed: 
>  This transaction only concerns a single account. Please select multiple accounts to complete the transaction.

Journal voucher line accounts are not successfully cleared and the module is in an unknown state. 

After researching this it looks like this happens whenever the clear button is pressed.

**Comment by jniles** [comment]
Hmmm..... clear() likely doesn't clear error messages.  Should be an easy
fix.

On Jan 31, 2017 21:28, "Steven Fountain" <notifications@github.com> wrote:

The complex journal vouchers module does not successfully reset after a
voucher has been created.

After completing a journal voucher the following message is displayed:

This transaction only concerns a single account. Please select multiple
accounts to complete the transaction.

Journal voucher line accounts are not successfully cleared and the module
is in an unknown state.

After researching this it looks like this happens whenever the clear button
is pressed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Vanga-Hospital/bhima-2.X/issues/232>, or mute the thread
